/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lvlpackages;

import Game.JDBC;
import Game.WPM;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;



/**
 *
 * @author HP
 */
public class MatchingFrame extends javax.swing.JFrame implements ActionListener {
    JButton[][]butArray = new JButton[5][5];

    int size=4;
    int userLevel=5;
    int btnLevel=0;
    String querry;
    int lvll;

    /**
     * Creates new form MatchingFrame
     */
    public MatchingFrame() {
        initComponents();
        initialize();
    }
    
    private void initialize(){
        gamePAN.setLayout(new GridLayout(size,size));
        for(int r=1; r<size+1;r++)
            for(int c=1; c<size+1;c++){
                btnLevel=btnLevel+1;
                butArray[r][c]=new JButton("Level"+btnLevel);

                butArray[r][c].addActionListener(this);
                butArray[r][c].setSize(250,250);

                colorizeButton(r,c,btnLevel);

                //btnIndex++;
                gamePAN.add(butArray[r][c]);
            }
        validate();
    }

    private void colorizeButton(int r, int c,int btnLevel) {
        int user_GetLevel =  JDBC.LastPlayedLvl(1);
        if(user_GetLevel == btnLevel){
            butArray[r][c].setBackground(new Color(107, 207, 105));
        }else{
                butArray[r][c].setBackground(new Color(156, 189, 247));
        }
    }

    public int getTest(int level) throws ClassNotFoundException, SQLException{
//           System.out.println(lvl);
            return level;
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        for(int r=1;r<size+1;r++)
            for(int c=1;c<size+1;c++){
                if(ae.getSource()==butArray[r][c]){
                switch (r) {
                        case 1:
                        {
                            try {
                              lvll =   getTest(c);


                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(MatchingFrame.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (SQLException ex) {
                                Logger.getLogger(MatchingFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                            break;

                        case 2:
                            {
                            try {
                                lvll = getTest(size+c);

                            } catch (ClassNotFoundException | SQLException ex) {
                                Logger.getLogger(MatchingFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }
                            break;
                        case 3:
                        {
                            try{
                                lvll = getTest(size*2+c);
                            } catch(ClassNotFoundException | SQLException ex){
                                Logger.getLogger(MatchingFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }
                            break;
                        case 4:

                            {
                            try{

                                getTest(size*3+c);
                            } catch(ClassNotFoundException | SQLException ex){
                                Logger.getLogger(MatchingFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }
                            break;
                        default:
                            break;
                    }
                    showGUI();

                }
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePAN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout gamePANLayout = new javax.swing.GroupLayout(gamePAN);
        gamePAN.setLayout(gamePANLayout);
        gamePANLayout.setHorizontalGroup(
            gamePANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        gamePANLayout.setVerticalGroup(
            gamePANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jLabel1.setText("Quelle est votre niveau ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gamePAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(gamePAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatchingFrame().setVisible(true);
            }
        });
    }


    private javax.swing.JPanel gamePAN;
    private javax.swing.JLabel jLabel1;


    public void showGUI()
    {
       dispose();
    WPM wpm = new WPM(lvll<=10?lvll:0);

    }



}
